### ISSUE TITLE
Existing users login issues

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-google#11]
As we know, some existing users are experiencing login issues after the migration.  Relevant [slack thread](https://roamresearch.slack.com/archives/C016N2B66JU/p1689583969977039).

Users in the thread have mentioned
 - that they can log in via different browser (or incognito)
 - clearing cookies / cache did not help

I imagine the issue has something to do with a pre-existing `roamjs:oauth-google:{graph}` local storage object.

Noting my superficial exploration so far for future me:
 - index.ts > `settings.panel.create` (Log in) > roamjs-components `OauthPanel`

Probably related: https://github.com/RoamJS/google/issues/9
Tagging @dvargas92495 for visibility as he was working on this issue recently

**Comment by dvargasfuertes** [comment]
if it has to do with local storage, logging out and back in should fix. I'm seeing some undefined errors now
![Screenshot 2023-07-25 at 10 39 18 PM](https://github.com/RoamJS/google/assets/7143571/144861fa-e37d-48f2-9b04-8c6698c72293)

**Comment by dvargasfuertes** [comment]
Actually that id issue is Dropbox related and should now be fixed. I'll keep an eye out for any google-related emails

**Comment by mdroidian** [comment]
When I log out and log back into Roam, or `Delete all ... ` from https://myaccount.google.com/connections, the localStorage key still exists.

https://github.com/RoamJS/google/assets/3792666/59f3ba22-e458-4492-be04-1f806c0b8dbc



But I am now doubting my original hypothesis because the user is reporting seeing `"Login with Google"` which seems to only exist when the value is empty.

**Comment by dvargasfuertes** [comment]
it's probably disappears bc it's crashing after the error - it's existence is not dependent on whether there's a value set there or not.

That 500 should be a clue - let's see if there are any errors sent

**Comment by mdroidian** [comment]
Here's what I meant about the value being set:
If I remove the value, I see `Login with Google`.
If I set a fake value, I see `Add Another Google Account` as if I'm logged in.

https://github.com/RoamJS/google/assets/3792666/8571f7c1-3492-4a1b-81f4-9c90fdf1e602

**RE: 500 error**
Nice catch, I wasn't looking for that.  More often than not it doesn't show up.  And it doesn't seem to affect my ability to login.

https://github.com/RoamJS/google/assets/3792666/252af9f6-1689-4208-a0ad-18a1458c5881

**Continued auth request**
Another think I noticed is that sometimes it will continue requesting. @ 45 seconds in

https://github.com/RoamJS/google/assets/3792666/5484bd0e-ab13-4e9f-9f2c-e43601e4e950

**Comment by mdroidian** [comment]
Should be fixed with: https://github.com/RoamJS/google/pull/36
