### ISSUE TITLE
Can not log in google 

### ISSUE THREAD

**Issue by yikun-baio** [dvargas92495/roamjs-google#9]
<img width="586" alt="Screenshot 2023-07-20 at 11 43 57 AM" src="https://github.com/RoamJS/google/assets/31041246/84663d90-6410-43ea-ac3e-5c7e578a74ac">

**Comment by dvargasfuertes** [comment]
Hey @Baio0 

We've pushed some changes hoping to address - give it another try when you get a chance

**Comment by mdroidian** [comment]
@yikun-baio has this been resolved?

**Comment by mandliya** [comment]
Still seeing this problem. Appreciate the extension @dvargas92495

**Comment by nhurdler9** [comment]
Also seeing the same problem... @dvargas92495  404 error when I select all (cal/drive/etc) in the menu. J

**Comment by mdroidian** [comment]
Are you using the app or browser?

**Comment by mdroidian** [comment]
Fixed: https://github.com/RoamJS/google/pull/36
